name: chicago_delights
description: Food ordering app for Chicago Delight's Pizza & Grillz

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  firebase_core: ^2.13.0
  cloud_firestore: ^4.8.1
  firebase_auth: ^4.7.3
  razorpay_flutter: ^1.3.7
  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/